apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: onlineeventbooking-i221242-anooshaali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: anooshaaali293/cs4067-assignment-02-22i-1242-anooshaali-booking-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:123456@postgres-service:5432/booking_db"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: onlineeventbooking-i221242-anooshaali
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
