apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: onlineeventbooking-i221242-anooshaali
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: anooshaaali/cs4067-assignment-02-22i-1242-anooshaali-user-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: event-config
            - secretRef:
                name: event-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: onlineeventbooking-i221242-anooshaali
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
