apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: onlineeventbooking-i221242-anooshaali
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:latest
          command: ["sh", "-c", "until pg_isready -h postgres-service -p 5432; do sleep 2; done"]
        - name: create-db
          image: postgres:latest
          command: ["sh", "-c", "psql postgresql://postgres:123456@postgres-service:5432 -c 'CREATE DATABASE user_service_db;' || true"]
      containers:
        - name: user-service
          image: anooshaaali293/cs4067-assignment-02-22i-1242-anooshaali-user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:123456@postgres-service:5432/user_service_db"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: onlineeventbooking-i221242-anooshaali
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
