apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: localhost/-service
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:123456@postgres-db:5432/booking_db"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP
