apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: onlineeventbooking-i221242-anooshaali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: frontend-storage
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-config
      volumes:
        - name: frontend-storage
          emptyDir: {}
        - name: nginx-config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: onlineeventbooking-i221242-anooshaali
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
