version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user_service_db
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend 
    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: events_db
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
  
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    
  user-service:
    build: ./UserService
    container_name: user-service
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:123456@postgres:5432/user_service_db
    ports: 
      - "8000:8000"
    networks:
      - backend
  
  event-service:
    build: ./EventService
    container_name: event-service
    restart: always
    depends_on: 
      - mongodb
    environment:
      MONGO_URI: mongodb://mongo:27017/events_db
    ports:
      -"5002:5002"
    netw




