version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user_service_db
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend 
    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports

