version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user_service_db
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend 
    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
  
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    
  user-service:
    

